flowstablize_mode: 1
profile_hack_enabled: false
skin_enabled: false
gesture_enabled: true
initial_min_score: 5
initial_detect_frames: 6
initial_reject_frames: 6
min_flow: 5
min_face_width: 9
min_face_height: 9
max_face_width: 100
max_face_height: 100
debug_mode: 6
meas_cov: 1.0
proc_cov: 0.05
start_paused: true
