update_freq: 15.0
initial_mode: 0
joy_override_buttion: 7
joy_override_timeout: 15.0
idle_timeout: 10
servo_desired_depth: 2.5
#target_height: 1.1
#target_dist_ground: 0.7
target_height: 1.5
target_dist_ground: 0.75
stale_video_timeout: 10.0
