# if abs_yaw_ctrl is true: theta is used over vw
# if abs_alt_ctrl is true: alt is used over vz
# All values are metric, angles are in radians
abs_yaw_ctrl: false
abs_abs_ctrl: false
plan:
  -
    action: 'wait'
    duration: 10
  -
    action: 'takeoff'
    duration: 5
  -
    action: 'vel'
    target: {vx: 0.0, vy: 0.0, vw: 0.0, vz: 0.2}
    duration: 1
  -
    action: 'stop'
    duration: 1
  -
    action: 'vel'
    duration: 3
    target: {vx: 0.2, vy: 0.0, vw: 0.0, vz: 0.0}
  -
    action: 'stop'
    duration: 2
  -
    action: 'vel'
    duration: 3
    target: {vx: 0.0, vy: -0.2, vw: 0.0, vz: 0.0}
  -
    action: 'stop'
    duration: 2
  -
    action: 'vel'
    duration: 3
    target: {vx: -0.2, vy: 0.0, vw: 0.0, vz: 0.0}
  -
    action: 'stop'
    duration: 2
  -
    action: 'vel'
    duration: 3
    target: {vx: 0.0, vy: 0.2, vw: 0.0, vz: 0.0}
  -
    action: 'stop'
    duration: 2
  -
    action: 'land'
    duration: 2
